### ISSUE TITLE
Shouldnt these be scripts?

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/framework#35]
Sorry for the ignorance but I was just thinking about this and... shouldnt these imagens like -ASUS, -Surface and -framework be patchsets over the -main images? Something like Startingpoint does with it's bling module instead of having new images just for those things?

**Comment by bobslept** [comment]
Maybe I don't totally understand but in this setup we create images from main, but also from bluefin or bazzite, with specific features for specific devices. For example the surface and asus ones also delivers custom kernels in them.

**Comment by castrojo** [comment]
> be patchsets over the -main images?

That's what they are! :smile:

**Comment by castrojo** [comment]
Ok I have time to answer this now in more detail. So in the old world, sure.

But in this world the value is running the script everyday and then stamping out an image, so that we know that it built. If it was a script you'd have to make sure everyone ran it, or what happens if someone cancels it or there's an error. That's an entire class of errors that users never have to deal with again. 

The UX kind of sucks because now users have to care about a specific image, so what I'm hoping for in the future is if we can detect if you're on a surface the updater updates you to that in the background, that kind of thing.

**Comment by tulilirockz** [comment]
Makes sense! Closing this as it got explained LOL
